//! Literal port of kernels/portable/cpu/op_asin.cpp.

use crate::kernels::portable::cpu::pattern::pattern::unary_ufunc_realhbbf16_to_floathbf16;
use crate::runtime::core::portable_type::tensor::Tensor;
use crate::runtime::kernel::kernel_runtime_context::KernelRuntimeContext;

// PORT-NOTE: `DEFINE_UNARY_UFUNC_REALHBBF16_TO_FLOATHBF16(asin_out, std::asin)`
// expands to a kernel fn forwarding to
// `internal::unary_ufunc_realhbbf16_to_floathbf16(std::asin, std::asin, ...)`.
// `std::asin` is passed as both the float and double function pointers
// (`f32::asin` / `f64::asin`).

// [spec:et:def:op-asin.torch.executor.native.asin-out-fn]
// [spec:et:sem:op-asin.torch.executor.native.asin-out-fn]
pub fn asin_out<'a, 'b>(
    ctx: &mut KernelRuntimeContext,
    in_: &Tensor,
    out: &'a Tensor<'b>,
) -> &'a Tensor<'b> {
    unary_ufunc_realhbbf16_to_floathbf16(f32::asin, f64::asin, ctx, in_, out)
}

// PORT-NOTE: the C++ test suite is generated by
// `IMPLEMENT_UNARY_UFUNC_REALHB_TO_FLOATH_TEST(OpAsinOutTest)`, which mixes in the
// shared `UnaryUfuncRealHBBF16ToFloatHBF16Test` harness
// (kernels/test/UnaryUfuncRealHBBF16ToFloatHBF16Test.{h,cpp}). The Rust port hosts
// that harness in `pattern::unary_ufunc_realhbbf16_to_floathbf16::test_harness`;
// this suite mirrors op_atan.rs with `op_out = asin_out` and `op_reference =
// f64::asin`.
#[cfg(test)]
mod tests {
    use super::*;
    use crate::kernels::portable::cpu::pattern::unary_ufunc_realhbbf16_to_floathbf16::test_harness as harness;

    fn op_out<'a, 'b>(
        ctx: &mut KernelRuntimeContext,
        self_: &Tensor,
        out: &'a Tensor<'b>,
    ) -> &'a Tensor<'b> {
        asin_out(ctx, self_, out)
    }

    fn op_reference(x: f64) -> f64 {
        x.asin()
    }

    // [spec:et:sem:op-asin.torch.executor.native.asin-out-fn/test]
    #[test]
    fn op_asin_out_test_handle_bool_input() {
        harness::test_bool_input(op_out, op_reference);
    }

    // [spec:et:sem:op-asin.torch.executor.native.asin-out-fn/test]
    #[test]
    fn op_asin_out_test_all_real_input_half_output_static_dynamism_support() {
        harness::test_all_real_input_half_output_static_dynamism_support(op_out, op_reference);
    }

    // [spec:et:sem:op-asin.torch.executor.native.asin-out-fn/test]
    #[test]
    fn op_asin_out_test_all_real_input_bfloat16_output_static_dynamism_support() {
        harness::test_all_real_input_bfloat16_output_static_dynamism_support(op_out, op_reference);
    }

    // [spec:et:sem:op-asin.torch.executor.native.asin-out-fn/test]
    #[test]
    fn op_asin_out_test_all_real_input_float_output_static_dynamism_support() {
        harness::test_all_real_input_float_output_static_dynamism_support(op_out, op_reference);
    }

    // [spec:et:sem:op-asin.torch.executor.native.asin-out-fn/test]
    #[test]
    fn op_asin_out_test_all_real_input_double_output_static_dynamism_support() {
        harness::test_all_real_input_double_output_static_dynamism_support(op_out, op_reference);
    }

    // [spec:et:sem:op-asin.torch.executor.native.asin-out-fn/test]
    #[test]
    fn op_asin_out_test_all_real_input_bfloat16_output_bound_dynamism_support() {
        harness::test_all_real_input_bfloat16_output_bound_dynamism_support(op_out, op_reference);
    }

    // [spec:et:sem:op-asin.torch.executor.native.asin-out-fn/test]
    #[test]
    fn op_asin_out_test_all_real_input_float_output_bound_dynamism_support() {
        harness::test_all_real_input_float_output_bound_dynamism_support(op_out, op_reference);
    }

    // [spec:et:sem:op-asin.torch.executor.native.asin-out-fn/test]
    #[test]
    fn op_asin_out_test_all_real_input_double_output_bound_dynamism_support() {
        harness::test_all_real_input_double_output_bound_dynamism_support(op_out, op_reference);
    }

    // [spec:et:sem:op-asin.torch.executor.native.asin-out-fn/test]
    #[test]
    fn op_asin_out_test_all_real_input_float_output_unbound_dynamism_support() {
        harness::test_all_real_input_float_output_unbound_dynamism_support(op_out, op_reference);
    }

    // [spec:et:sem:op-asin.torch.executor.native.asin-out-fn/test]
    #[test]
    fn op_asin_out_test_all_real_input_double_output_unbound_dynamism_support() {
        harness::test_all_real_input_double_output_unbound_dynamism_support(op_out, op_reference);
    }

    // [spec:et:sem:op-asin.torch.executor.native.asin-out-fn/test]
    #[test]
    fn op_asin_out_test_all_non_float_output_dtype_dies() {
        harness::test_non_float_output_dtype_dies(op_out);
    }

    // [spec:et:sem:op-asin.torch.executor.native.asin-out-fn/test]
    #[test]
    fn op_asin_out_test_mismatched_input_shapes_dies() {
        harness::test_mismatched_input_shapes_dies(op_out);
    }
}
