//! Literal port of kernels/portable/cpu/op_atan.cpp.

use crate::kernels::portable::cpu::pattern::pattern::unary_ufunc_realhbbf16_to_floathbf16;
use crate::runtime::core::portable_type::tensor::Tensor;
use crate::runtime::kernel::kernel_runtime_context::KernelRuntimeContext;

// PORT-NOTE: `DEFINE_UNARY_UFUNC_REALHBBF16_TO_FLOATHBF16(atan_out, std::atan)`
// expands to a kernel fn forwarding to
// `internal::unary_ufunc_realhbbf16_to_floathbf16(std::atan, std::atan, ...)`.
// `std::atan` is passed as both the float and double function pointers
// (`f32::atan` / `f64::atan`).

// [spec:et:def:op-atan.torch.executor.native.atan-out-fn]
// [spec:et:sem:op-atan.torch.executor.native.atan-out-fn]
pub fn atan_out<'a, 'b>(
    ctx: &mut KernelRuntimeContext,
    in_: &Tensor,
    out: &'a Tensor<'b>,
) -> &'a Tensor<'b> {
    unary_ufunc_realhbbf16_to_floathbf16(f32::atan, f64::atan, ctx, in_, out)
}

// PORT-NOTE: the C++ test suite is generated by
// `IMPLEMENT_UNARY_UFUNC_REALHB_TO_FLOATH_TEST(OpAtanOutTest)`, which mixes in the
// shared `UnaryUfuncRealHBBF16ToFloatHBF16Test` harness
// (kernels/test/UnaryUfuncRealHBBF16ToFloatHBF16Test.{h,cpp}). There is no shared
// cross-module test harness in the Rust port (each op module owns its tests, per
// the op_abs.rs/op_ceil.rs precedent), so the harness is inlined below with
// `op_out = atan_out` and `op_reference = f64::atan`.
#[cfg(test)]
mod tests {
    use super::*;
    use crate::kernels::portable::cpu::pattern::unary_ufunc_realhbbf16_to_floathbf16::test_harness as harness;

    fn op_out<'a, 'b>(
        ctx: &mut KernelRuntimeContext,
        self_: &Tensor,
        out: &'a Tensor<'b>,
    ) -> &'a Tensor<'b> {
        atan_out(ctx, self_, out)
    }

    fn op_reference(x: f64) -> f64 {
        x.atan()
    }

    // [spec:et:sem:op-atan.torch.executor.native.atan-out-fn/test]
    #[test]
    fn op_atan_out_test_handle_bool_input() {
        harness::test_bool_input(op_out, op_reference);
    }

    // [spec:et:sem:op-atan.torch.executor.native.atan-out-fn/test]
    #[test]
    fn op_atan_out_test_all_real_input_half_output_static_dynamism_support() {
        harness::test_all_real_input_half_output_static_dynamism_support(op_out, op_reference);
    }

    // [spec:et:sem:op-atan.torch.executor.native.atan-out-fn/test]
    #[test]
    fn op_atan_out_test_all_real_input_bfloat16_output_static_dynamism_support() {
        harness::test_all_real_input_bfloat16_output_static_dynamism_support(op_out, op_reference);
    }

    // [spec:et:sem:op-atan.torch.executor.native.atan-out-fn/test]
    #[test]
    fn op_atan_out_test_all_real_input_float_output_static_dynamism_support() {
        harness::test_all_real_input_float_output_static_dynamism_support(op_out, op_reference);
    }

    // [spec:et:sem:op-atan.torch.executor.native.atan-out-fn/test]
    #[test]
    fn op_atan_out_test_all_real_input_double_output_static_dynamism_support() {
        harness::test_all_real_input_double_output_static_dynamism_support(op_out, op_reference);
    }

    // [spec:et:sem:op-atan.torch.executor.native.atan-out-fn/test]
    #[test]
    fn op_atan_out_test_all_real_input_bfloat16_output_bound_dynamism_support() {
        harness::test_all_real_input_bfloat16_output_bound_dynamism_support(op_out, op_reference);
    }

    // [spec:et:sem:op-atan.torch.executor.native.atan-out-fn/test]
    #[test]
    fn op_atan_out_test_all_real_input_float_output_bound_dynamism_support() {
        harness::test_all_real_input_float_output_bound_dynamism_support(op_out, op_reference);
    }

    // [spec:et:sem:op-atan.torch.executor.native.atan-out-fn/test]
    #[test]
    fn op_atan_out_test_all_real_input_double_output_bound_dynamism_support() {
        harness::test_all_real_input_double_output_bound_dynamism_support(op_out, op_reference);
    }

    // [spec:et:sem:op-atan.torch.executor.native.atan-out-fn/test]
    #[test]
    fn op_atan_out_test_all_real_input_float_output_unbound_dynamism_support() {
        harness::test_all_real_input_float_output_unbound_dynamism_support(op_out, op_reference);
    }

    // [spec:et:sem:op-atan.torch.executor.native.atan-out-fn/test]
    #[test]
    fn op_atan_out_test_all_real_input_double_output_unbound_dynamism_support() {
        harness::test_all_real_input_double_output_unbound_dynamism_support(op_out, op_reference);
    }

    // [spec:et:sem:op-atan.torch.executor.native.atan-out-fn/test]
    #[test]
    fn op_atan_out_test_all_non_float_output_dtype_dies() {
        harness::test_non_float_output_dtype_dies(op_out);
    }

    // [spec:et:sem:op-atan.torch.executor.native.atan-out-fn/test]
    #[test]
    fn op_atan_out_test_mismatched_input_shapes_dies() {
        harness::test_mismatched_input_shapes_dies(op_out);
    }
}
