#!/usr/bin/env python3
"""Supplement plan/.port-manifest.styx with macro-generated kernel functions.

`nplan port extract` is AST-based, so kernel entry points generated by the
DEFINE_UNARY_UFUNC_* macros in kernels/portable/cpu/pattern/pattern.h have no
function node to extract and are missing from the manifest. This script walks
the kernel registration YAMLs (the authoritative op inventory), finds kernel
functions the manifest lacks, locates their macro invocation site, and inserts
synthesized manifest entries so `nplan port markup` and the wave gates cover
them.

Idempotent, and safe to re-run; extraction rewrites the manifest, so re-run
this after every `nplan port extract`:

    nplan port extract && python3 plan/supplement-manifest.py && nplan port markup
"""

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MANIFEST = REPO / "plan" / ".port-manifest.styx"
KERNEL_YAMLS = [
    REPO / "kernels" / "portable" / "functions.yaml",
    REPO / "kernels" / "portable" / "custom_ops.yaml",
    REPO / "kernels" / "quantized" / "quantized.yaml",
]
KERNEL_SRC_DIRS = [
    REPO / "kernels" / "portable" / "cpu",
    REPO / "kernels" / "quantized" / "cpu",
]

# Macro invocation defining a kernel function: e.g.
#   DEFINE_UNARY_UFUNC_REALHBF16(ceil_out, std::ceil)
MACRO_DEF = re.compile(r"^\s*([A-Z][A-Z_0-9]*)\(\s*(\w+)\s*[,)]")


def slugify(name: str) -> str:
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", name)
    return s.replace("_", "-").lower()


def yaml_kernel_names() -> set[str]:
    names = set()
    for path in KERNEL_YAMLS:
        if not path.exists():
            continue
        for line in path.read_text().splitlines():
            m = re.match(r"\s*kernel_name:\s*(\S+)", line)
            if m:
                names.add(m.group(1).split("::")[-1])
    return names


def manifest_fn_names(text: str) -> set[str]:
    return set(re.findall(r"\{id \S+, kind @function, name (\w+),", text))


def find_macro_sites(missing: set[str]) -> dict[str, tuple[Path, int, str]]:
    sites = {}
    for src_dir in KERNEL_SRC_DIRS:
        for path in sorted(src_dir.glob("*.cpp")):
            for lineno, line in enumerate(path.read_text().splitlines(), 1):
                m = MACRO_DEF.match(line)
                if m and m.group(2) in missing:
                    sites[m.group(2)] = (path, lineno, m.group(1))
    return sites


def entry_for(fn: str, path: Path, lineno: int, macro: str) -> tuple[str, int, str]:
    rel = path.relative_to(REPO).as_posix()
    module = slugify(path.stem)
    leaf = slugify(fn)
    # Every kernel .cpp defines its ops inside torch::executor::native.
    rule_id = f"{module}.torch.executor.native.{leaf}-fn"
    qualified = f"torch.executor.native.{leaf}"
    signature = f"Tensor& {fn}(KernelRuntimeContext& ctx, const Tensor& in, Tensor& out) [generated by {macro}]"
    block = (
        f"    {{id {rule_id}, kind @function, name {fn}, "
        f"qualified {qualified}, signature \"{signature}\", "
        f"file {rel}, line_start {lineno}, line_end {lineno}, rules (\n"
        f"        {{verb def, id {rule_id}}}\n"
        f"        {{verb sem, id {rule_id}}}\n"
        f"    )}}"
    )
    return rel, lineno, block


def insert_entries(text: str, entries: list[tuple[str, int, str]]) -> str:
    # Split the symbols list into whole entry blocks; each starts with
    # "    {id " and ends with a "    )}" line.
    lines = text.splitlines(keepends=True)
    head, blocks, tail = [], [], []
    cur, state = [], "head"
    for line in lines:
        if state == "head":
            head.append(line)
            if line.startswith("symbols ("):
                state = "body"
        elif state == "body":
            if line.startswith(")"):
                tail.append(line)
                state = "tail"
            else:
                cur.append(line)
                if line.startswith("    )}"):
                    blocks.append("".join(cur))
                    cur = []
        else:
            tail.append(line)
    if cur:
        blocks.append("".join(cur))

    def key(block: str) -> tuple[str, int, str]:
        m = re.search(r"\{id (\S+),.* file (\S+), line_start (\d+)", block, re.DOTALL)
        return (m.group(2), int(m.group(3)), m.group(1))

    for _, _, block in entries:
        blocks.append(block + "\n")
    blocks.sort(key=key)
    return "".join(head) + "".join(blocks) + "".join(tail)


def main() -> int:
    text = MANIFEST.read_text()
    missing = yaml_kernel_names() - manifest_fn_names(text)
    if not missing:
        print("manifest already covers every YAML kernel function")
        return 0
    sites = find_macro_sites(missing)
    unlocated = sorted(missing - sites.keys())
    entries = [entry_for(fn, *sites[fn]) for fn in sorted(sites)]
    MANIFEST.write_text(insert_entries(text, entries))
    print(f"added {len(entries)} macro-generated kernel(s) to {MANIFEST.relative_to(REPO)}")
    for fn in sorted(sites):
        rel, lineno, _ = entry_for(fn, *sites[fn])
        print(f"  {fn}  ({rel}:{lineno})")
    if unlocated:
        print(f"WARNING: {len(unlocated)} YAML kernel(s) not found in the manifest "
              f"or at any macro site: {', '.join(unlocated)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
