//! Literal port of runtime/core/exec_aten/util/scalar_type_util.h.
//!
//! Forked from c10/core/ScalarType.h. This file contains all of the
//! non-critical parts of the original ScalarType.h that are not required for the
//! core ExecuTorch runtime, but may be helpful for code that uses ScalarType.

use crate::runtime::core::portable_type::bits_types::{bits1x8, bits2x4, bits4x2, bits8, bits16};
use crate::runtime::core::portable_type::qint_types::{qint8, qint32, quint2x4, quint4x2, quint8};
use crate::runtime::core::portable_type::scalar_type::{ScalarType, unused_dtype};
use crate::runtime::core::portable_type::{
    BFloat16, ComplexDouble, ComplexFloat, ComplexHalf, Half,
};

// PORT-NOTE: `ET_CHECK`/`ET_CHECK_MSG` live in runtime/platform/assert.h, which
// has no ported `assert.rs` target yet. These local macros mirror the semantics
// (emit message, then abort via the PAL abort path), matching the pattern used
// in runtime/core/portable_type/scalar.rs. Should be replaced by the shared
// `et_check_msg!`/`et_check!` once the assert module is ported. Unresolved
// cross-module reference.
macro_rules! et_check_msg {
    ($cond:expr, $($arg:tt)*) => {
        if !($cond) {
            crate::runtime::platform::abort::runtime_abort();
        }
    };
}

macro_rules! et_check {
    ($cond:expr) => {
        if !($cond) {
            crate::runtime::platform::abort::runtime_abort();
        }
    };
}

//
// ScalarTypeToCppType / CppTypeToScalarType
//
// The C++ `ScalarTypeToCppType<N>` and `CppTypeToScalarType<T>` template maps
// (generated by `ET_FORALL_SCALAR_TYPES`) are modeled here as the
// `CppTypeToScalarType` trait plus the concrete type aliases bound by the
// `et_scalar_type_cpp_type!` alias helper used inside the switch macros.
//

/// Maps C++ types to ScalarTypes.
// [spec:et:def:scalar-type-util.executorch.runtime.can-cast] (see can_cast below)
pub trait CppTypeToScalarType {
    const VALUE: ScalarType;
}

macro_rules! specialize_cpp_type_to_scalar_type {
    ($cpp_type:ty, $scalar_type:ident) => {
        impl CppTypeToScalarType for $cpp_type {
            const VALUE: ScalarType = ScalarType::$scalar_type;
        }
    };
}

specialize_cpp_type_to_scalar_type!(u8, Byte);
specialize_cpp_type_to_scalar_type!(i8, Char);
specialize_cpp_type_to_scalar_type!(i16, Short);
specialize_cpp_type_to_scalar_type!(i32, Int);
specialize_cpp_type_to_scalar_type!(i64, Long);
specialize_cpp_type_to_scalar_type!(Half, Half);
specialize_cpp_type_to_scalar_type!(f32, Float);
specialize_cpp_type_to_scalar_type!(f64, Double);
specialize_cpp_type_to_scalar_type!(ComplexHalf, ComplexHalf);
specialize_cpp_type_to_scalar_type!(ComplexFloat, ComplexFloat);
specialize_cpp_type_to_scalar_type!(ComplexDouble, ComplexDouble);
specialize_cpp_type_to_scalar_type!(bool, Bool);
specialize_cpp_type_to_scalar_type!(qint8, QInt8);
specialize_cpp_type_to_scalar_type!(quint8, QUInt8);
specialize_cpp_type_to_scalar_type!(qint32, QInt32);
specialize_cpp_type_to_scalar_type!(BFloat16, BFloat16);
specialize_cpp_type_to_scalar_type!(quint4x2, QUInt4x2);
specialize_cpp_type_to_scalar_type!(quint2x4, QUInt2x4);
specialize_cpp_type_to_scalar_type!(bits1x8, Bits1x8);
specialize_cpp_type_to_scalar_type!(bits2x4, Bits2x4);
specialize_cpp_type_to_scalar_type!(bits4x2, Bits4x2);
specialize_cpp_type_to_scalar_type!(bits8, Bits8);
specialize_cpp_type_to_scalar_type!(bits16, Bits16);
specialize_cpp_type_to_scalar_type!(unused_dtype::Float8_e5m2, Float8_e5m2);
specialize_cpp_type_to_scalar_type!(unused_dtype::Float8_e4m3fn, Float8_e4m3fn);
specialize_cpp_type_to_scalar_type!(unused_dtype::Float8_e5m2fnuz, Float8_e5m2fnuz);
specialize_cpp_type_to_scalar_type!(unused_dtype::Float8_e4m3fnuz, Float8_e4m3fnuz);
specialize_cpp_type_to_scalar_type!(u16, UInt16);
specialize_cpp_type_to_scalar_type!(u32, UInt32);
specialize_cpp_type_to_scalar_type!(u64, UInt64);

//
// Utility functions to retrieve metadata for a given ScalarType
//

/// Returns true if the parameter is one of the values covered by
/// ET_FORALL_SCALAR_TYPES.
// [spec:et:def:scalar-type-util.executorch.runtime.is-valid-fn]
// [spec:et:sem:scalar-type-util.executorch.runtime.is-valid-fn]
pub fn is_valid(ty: ScalarType) -> bool {
    // PORT-NOTE: C++ compares `type < ScalarType::NumOptions` on the enum; the
    // Rust `ScalarType` does not derive `PartialOrd`, so the comparison is
    // performed on the underlying `i8` discriminants (same ordering).
    (ty as i8) >= 0 && (ty as i8) < (ScalarType::NumOptions as i8) && ty != ScalarType::Undefined
}

/// Returns the name of a ScalarType as a C string.
// [spec:et:def:scalar-type-util.executorch.runtime.to-string-fn]
// [spec:et:sem:scalar-type-util.executorch.runtime.to-string-fn]
pub fn to_string(t: ScalarType) -> &'static str {
    match t {
        ScalarType::Byte => "Byte",
        ScalarType::Char => "Char",
        ScalarType::Short => "Short",
        ScalarType::Int => "Int",
        ScalarType::Long => "Long",
        ScalarType::Half => "Half",
        ScalarType::Float => "Float",
        ScalarType::Double => "Double",
        ScalarType::ComplexHalf => "ComplexHalf",
        ScalarType::ComplexFloat => "ComplexFloat",
        ScalarType::ComplexDouble => "ComplexDouble",
        ScalarType::Bool => "Bool",
        ScalarType::QInt8 => "QInt8",
        ScalarType::QUInt8 => "QUInt8",
        ScalarType::QInt32 => "QInt32",
        ScalarType::BFloat16 => "BFloat16",
        ScalarType::QUInt4x2 => "QUInt4x2",
        ScalarType::QUInt2x4 => "QUInt2x4",
        ScalarType::Bits1x8 => "Bits1x8",
        ScalarType::Bits2x4 => "Bits2x4",
        ScalarType::Bits4x2 => "Bits4x2",
        ScalarType::Bits8 => "Bits8",
        ScalarType::Bits16 => "Bits16",
        ScalarType::Float8_e5m2 => "Float8_e5m2",
        ScalarType::Float8_e4m3fn => "Float8_e4m3fn",
        ScalarType::Float8_e5m2fnuz => "Float8_e5m2fnuz",
        ScalarType::Float8_e4m3fnuz => "Float8_e4m3fnuz",
        ScalarType::UInt16 => "UInt16",
        ScalarType::UInt32 => "UInt32",
        ScalarType::UInt64 => "UInt64",
        ScalarType::Undefined => "Undefined",
        // PORT-NOTE: The C++ `switch` has a `default` arm returning
        // "UNKNOWN_SCALAR" for any bit pattern not covered by
        // ET_FORALL_SCALAR_TYPES or Undefined. A Rust `#[repr(i8)]` enum can
        // only hold declared discriminants, so the match above is exhaustive
        // (NumOptions is the only remaining arm) and the "UNKNOWN_SCALAR"
        // fallthrough is only reachable via NumOptions.
        ScalarType::NumOptions => "UNKNOWN_SCALAR",
    }
}

/// Returns the size in bytes of the C type associated with the ScalarType.
///
/// Calls et_check_msg!() if the type is unknown or is ScalarType::Undefined.
// [spec:et:def:scalar-type-util.executorch.runtime.element-size-fn]
// [spec:et:sem:scalar-type-util.executorch.runtime.element-size-fn]
pub fn element_size(t: ScalarType) -> usize {
    match t {
        ScalarType::Byte => core::mem::size_of::<u8>(),
        ScalarType::Char => core::mem::size_of::<i8>(),
        ScalarType::Short => core::mem::size_of::<i16>(),
        ScalarType::Int => core::mem::size_of::<i32>(),
        ScalarType::Long => core::mem::size_of::<i64>(),
        ScalarType::Half => core::mem::size_of::<Half>(),
        ScalarType::Float => core::mem::size_of::<f32>(),
        ScalarType::Double => core::mem::size_of::<f64>(),
        ScalarType::ComplexHalf => core::mem::size_of::<ComplexHalf>(),
        ScalarType::ComplexFloat => core::mem::size_of::<ComplexFloat>(),
        ScalarType::ComplexDouble => core::mem::size_of::<ComplexDouble>(),
        ScalarType::Bool => core::mem::size_of::<bool>(),
        ScalarType::QInt8 => core::mem::size_of::<qint8>(),
        ScalarType::QUInt8 => core::mem::size_of::<quint8>(),
        ScalarType::QInt32 => core::mem::size_of::<qint32>(),
        ScalarType::BFloat16 => core::mem::size_of::<BFloat16>(),
        ScalarType::QUInt4x2 => core::mem::size_of::<quint4x2>(),
        ScalarType::QUInt2x4 => core::mem::size_of::<quint2x4>(),
        ScalarType::Bits1x8 => core::mem::size_of::<bits1x8>(),
        ScalarType::Bits2x4 => core::mem::size_of::<bits2x4>(),
        ScalarType::Bits4x2 => core::mem::size_of::<bits4x2>(),
        ScalarType::Bits8 => core::mem::size_of::<bits8>(),
        ScalarType::Bits16 => core::mem::size_of::<bits16>(),
        ScalarType::Float8_e5m2 => core::mem::size_of::<unused_dtype::Float8_e5m2>(),
        ScalarType::Float8_e4m3fn => core::mem::size_of::<unused_dtype::Float8_e4m3fn>(),
        ScalarType::Float8_e5m2fnuz => core::mem::size_of::<unused_dtype::Float8_e5m2fnuz>(),
        ScalarType::Float8_e4m3fnuz => core::mem::size_of::<unused_dtype::Float8_e4m3fnuz>(),
        ScalarType::UInt16 => core::mem::size_of::<u16>(),
        ScalarType::UInt32 => core::mem::size_of::<u32>(),
        ScalarType::UInt64 => core::mem::size_of::<u64>(),
        _ => {
            et_check_msg!(false, "Unknown ScalarType {}", t as i8);
            // et_check_msg! aborts; the C++ switch has no return here.
            unreachable!()
        }
    }
}

// [spec:et:def:scalar-type-util.executorch.runtime.is-integral-type]
// [spec:et:def:scalar-type-util.executorch.runtime.is-integral-type-fn]
// [spec:et:sem:scalar-type-util.executorch.runtime.is-integral-type-fn]
pub const fn is_integral_type(t: ScalarType, include_bool: bool) -> bool {
    (include_bool && matches!(t, ScalarType::Bool))
        || matches!(
            t,
            ScalarType::Byte
                | ScalarType::Char
                | ScalarType::Int
                | ScalarType::Long
                | ScalarType::Short
        )
}

// [spec:et:def:scalar-type-util.executorch.runtime.is-floating-point]
// [spec:et:def:scalar-type-util.executorch.runtime.is-reduced-floating-point]
// [spec:et:def:scalar-type-util.executorch.runtime.is-floating-type-fn]
// [spec:et:sem:scalar-type-util.executorch.runtime.is-floating-type-fn]
pub const fn is_floating_type(t: ScalarType) -> bool {
    matches!(
        t,
        ScalarType::Double | ScalarType::Float | ScalarType::Half | ScalarType::BFloat16
    )
}

// [spec:et:def:scalar-type-util.executorch.runtime.is-real-type-fn]
// [spec:et:sem:scalar-type-util.executorch.runtime.is-real-type-fn]
pub fn is_real_type(t: ScalarType) -> bool {
    matches!(
        t,
        ScalarType::Byte
            | ScalarType::Char
            | ScalarType::Short
            | ScalarType::Int
            | ScalarType::Long
            | ScalarType::Float
            | ScalarType::Double
    )
}

// [spec:et:def:scalar-type-util.executorch.runtime.is-real-h-type-fn]
// [spec:et:sem:scalar-type-util.executorch.runtime.is-real-h-type-fn]
pub fn is_real_h_type(t: ScalarType) -> bool {
    matches!(
        t,
        ScalarType::Byte
            | ScalarType::Char
            | ScalarType::Short
            | ScalarType::Int
            | ScalarType::Long
            | ScalarType::Float
            | ScalarType::Double
            | ScalarType::Half
    )
}

// [spec:et:def:scalar-type-util.executorch.runtime.is-real-hb-type-fn]
// [spec:et:sem:scalar-type-util.executorch.runtime.is-real-hb-type-fn]
pub fn is_real_hb_type(t: ScalarType) -> bool {
    is_real_h_type(t) || matches!(t, ScalarType::Bool)
}

// [spec:et:def:scalar-type-util.executorch.runtime.is-real-hbf16-type-fn]
// [spec:et:sem:scalar-type-util.executorch.runtime.is-real-hbf16-type-fn]
pub fn is_real_hbf16_type(t: ScalarType) -> bool {
    is_real_h_type(t) || matches!(t, ScalarType::BFloat16)
}

// [spec:et:def:scalar-type-util.executorch.runtime.is-real-hbbf16-type-fn]
// [spec:et:sem:scalar-type-util.executorch.runtime.is-real-hbbf16-type-fn]
pub fn is_real_hbbf16_type(t: ScalarType) -> bool {
    is_real_hb_type(t) || matches!(t, ScalarType::BFloat16)
}

// [spec:et:def:scalar-type-util.executorch.runtime.is-complex-type]
// [spec:et:def:scalar-type-util.executorch.runtime.is-complex-type-fn]
// [spec:et:sem:scalar-type-util.executorch.runtime.is-complex-type-fn]
pub const fn is_complex_type(t: ScalarType) -> bool {
    matches!(
        t,
        ScalarType::ComplexHalf | ScalarType::ComplexFloat | ScalarType::ComplexDouble
    )
}

// [spec:et:def:scalar-type-util.executorch.runtime.is-bits-type]
// [spec:et:def:scalar-type-util.executorch.runtime.is-bits-type-fn]
// [spec:et:sem:scalar-type-util.executorch.runtime.is-bits-type-fn]
pub const fn is_bits_type(t: ScalarType) -> bool {
    matches!(
        t,
        ScalarType::Bits1x8
            | ScalarType::Bits2x4
            | ScalarType::Bits4x2
            | ScalarType::Bits8
            | ScalarType::Bits16
    )
}

// [spec:et:def:scalar-type-util.executorch.runtime.is-qint-type]
// [spec:et:def:scalar-type-util.executorch.runtime.is-q-int-type-fn]
// [spec:et:sem:scalar-type-util.executorch.runtime.is-q-int-type-fn]
pub const fn is_qint_type(t: ScalarType) -> bool {
    // Don't forget to extend this when adding new QInt types
    matches!(
        t,
        ScalarType::QInt8
            | ScalarType::QUInt8
            | ScalarType::QInt32
            | ScalarType::QUInt4x2
            | ScalarType::QUInt2x4
    )
}

// [spec:et:def:scalar-type-util.executorch.runtime.is-float8-type]
// [spec:et:def:scalar-type-util.executorch.runtime.is-float8-type-fn]
// [spec:et:sem:scalar-type-util.executorch.runtime.is-float8-type-fn]
pub const fn is_float8_type(t: ScalarType) -> bool {
    // Don't forget to extend this when adding new QInt types
    matches!(
        t,
        ScalarType::Float8_e5m2
            | ScalarType::Float8_e4m3fn
            | ScalarType::Float8_e5m2fnuz
            | ScalarType::Float8_e4m3fnuz
    )
}

// [spec:et:def:scalar-type-util.executorch.runtime.is-barebones-unsigned-type]
// [spec:et:def:scalar-type-util.executorch.runtime.is-barebones-unsigned-type-fn]
// [spec:et:sem:scalar-type-util.executorch.runtime.is-barebones-unsigned-type-fn]
pub const fn is_barebones_unsigned_type(t: ScalarType) -> bool {
    // Don't forget to extend this when adding new QInt types
    matches!(
        t,
        ScalarType::UInt16 | ScalarType::UInt32 | ScalarType::UInt64
    )
}

// [spec:et:def:scalar-type-util.executorch.runtime.to-q-int-type-fn]
// [spec:et:sem:scalar-type-util.executorch.runtime.to-q-int-type-fn]
pub fn to_q_int_type(t: ScalarType) -> ScalarType {
    match t {
        ScalarType::Byte => ScalarType::QUInt8,
        ScalarType::Char => ScalarType::QInt8,
        ScalarType::Int => ScalarType::QInt32,
        _ => t,
    }
}

// [spec:et:def:scalar-type-util.executorch.runtime.to-underlying-fn]
// [spec:et:sem:scalar-type-util.executorch.runtime.to-underlying-fn]
pub fn to_underlying(t: ScalarType) -> ScalarType {
    match t {
        ScalarType::QUInt8 => ScalarType::Byte,
        ScalarType::QInt8 => ScalarType::Char,
        ScalarType::QInt32 => ScalarType::Int,
        ScalarType::QUInt4x2 => ScalarType::Byte,
        ScalarType::QUInt2x4 => ScalarType::Byte,
        _ => t,
    }
}

// [spec:et:def:scalar-type-util.executorch.runtime.is-signed-type-fn]
// [spec:et:sem:scalar-type-util.executorch.runtime.is-signed-type-fn]
pub fn is_signed_type(t: ScalarType) -> bool {
    et_check_msg!(
        !is_qint_type(t),
        "isSignedType not supported for quantized types like {}",
        t as i8
    );
    match t {
        ScalarType::ComplexHalf | ScalarType::ComplexFloat | ScalarType::ComplexDouble => true,
        // ET_FORALL_REAL_TYPES_AND3(Half, Bool, BFloat16, CASE_SIGNED):
        // `std::numeric_limits<ctype>::is_signed` for each mapped C++ type.
        ScalarType::Byte => false,  // uint8
        ScalarType::Char => true,   // int8
        ScalarType::Short => true,  // int16
        ScalarType::Int => true,    // int32
        ScalarType::Long => true,   // int64
        ScalarType::Float => true,  // float
        ScalarType::Double => true, // double
        ScalarType::Half => true,   // Half
        ScalarType::Bool => false,  // bool
        ScalarType::BFloat16 => true,
        _ => {
            et_check_msg!(false, "Unknown ScalarType {}", t as i8);
            unreachable!()
        }
    }
}

// [spec:et:def:scalar-type-util.executorch.runtime.is-underlying-fn]
// [spec:et:sem:scalar-type-util.executorch.runtime.is-underlying-fn]
pub fn is_underlying(ty: ScalarType, qtype: ScalarType) -> bool {
    ty == to_underlying(qtype)
}

// [spec:et:def:scalar-type-util.executorch.runtime.to-real-value-type-fn]
// [spec:et:sem:scalar-type-util.executorch.runtime.to-real-value-type-fn]
pub const fn to_real_value_type(t: ScalarType) -> ScalarType {
    match t {
        ScalarType::ComplexHalf => ScalarType::Half,
        ScalarType::ComplexFloat => ScalarType::Float,
        ScalarType::ComplexDouble => ScalarType::Double,
        _ => t,
    }
}

// [spec:et:def:scalar-type-util.executorch.runtime.to-complex-type-fn]
// [spec:et:sem:scalar-type-util.executorch.runtime.to-complex-type-fn]
pub fn to_complex_type(t: ScalarType) -> ScalarType {
    match t {
        ScalarType::BFloat16 => {
            // BFloat16 has range equivalent to Float,
            // so we map it to ComplexFloat.
            ScalarType::ComplexFloat
        }
        ScalarType::Half => ScalarType::ComplexHalf,
        ScalarType::Float => ScalarType::ComplexFloat,
        ScalarType::Double => ScalarType::ComplexDouble,
        ScalarType::ComplexHalf => ScalarType::ComplexHalf,
        ScalarType::ComplexFloat => ScalarType::ComplexFloat,
        ScalarType::ComplexDouble => ScalarType::ComplexDouble,
        _ => {
            et_check_msg!(false, "Unknown Complex ScalarType for {}", t as i8);
            unreachable!()
        }
    }
}

/// Encodes type casting rules that are consistent with ATen behaviour.
// [spec:et:def:scalar-type-util.executorch.runtime.can-cast-fn]
// [spec:et:sem:scalar-type-util.executorch.runtime.can-cast-fn]
pub const fn can_cast(from: ScalarType, to: ScalarType) -> bool {
    // Disallow complex -> non-complex
    !(is_complex_type(from) && !is_complex_type(to)) &&
        // Disallow float -> integral
        !(is_floating_type(from) && is_integral_type(to, /*includeBool=*/ false)) &&
        // Treat bool as a special category. Disallow non-bool -> bool
        !(!matches!(from, ScalarType::Bool) && matches!(to, ScalarType::Bool))
}

/// When casting from floating point to integral type, if the floating value is
/// outside the integral type range, then an error is thrown if sanitization is
/// enabled. To circumvent this, we cast the floating point to i64 first.
///
/// PORT-NOTE: The C++ `convert<To, From>` is a compile-time SFINAE-dispatched
/// template with two overloads (float->integral, and everything else). Rust has
/// no direct SFINAE analogue; the caller selects the right conversion path.
/// `convert_float_to_int` mirrors the float->integral overload
/// (`static_cast<To>(static_cast<int64_t>(val))`) and `convert` mirrors the
/// plain `static_cast<To>(val)` overload via the `From: Into<To>` bound.
// [spec:et:def:scalar-type-util.executorch.runtime.convert-fn]
// [spec:et:sem:scalar-type-util.executorch.runtime.convert-fn]
pub fn convert<To, From>(val: From) -> To
where
    From: Into<To>,
{
    val.into()
}

pub mod internal {
    use super::ScalarType;

    // This is generated according to NumPy's promote_types
    pub const U1: ScalarType = ScalarType::Byte;
    pub const I1: ScalarType = ScalarType::Char;
    pub const I2: ScalarType = ScalarType::Short;
    pub const I4: ScalarType = ScalarType::Int;
    pub const I8: ScalarType = ScalarType::Long;
    pub const F2: ScalarType = ScalarType::Half;
    pub const F4: ScalarType = ScalarType::Float;
    pub const F8: ScalarType = ScalarType::Double;
    pub const C2: ScalarType = ScalarType::ComplexHalf;
    pub const C4: ScalarType = ScalarType::ComplexFloat;
    pub const C8: ScalarType = ScalarType::ComplexDouble;
    pub const B1: ScalarType = ScalarType::Bool;
    pub const BF: ScalarType = ScalarType::BFloat16;

    pub const INDEX2DTYPE: [ScalarType; 13] = [U1, I1, I2, I4, I8, F2, F4, F8, C2, C4, C8, B1, BF];

    // [spec:et:def:scalar-type-util.executorch.runtime.internal.calculate-dtype2index-fn]
    // [spec:et:sem:scalar-type-util.executorch.runtime.internal.calculate-dtype2index-fn]
    pub const fn calculate_dtype2index() -> [i64; ScalarType::NumOptions as usize] {
        let mut inverse: [i64; ScalarType::NumOptions as usize] =
            [0; ScalarType::NumOptions as usize];
        let mut i: i64 = 0;
        while i < ScalarType::NumOptions as i64 {
            inverse[i as usize] = -1;
            i += 1;
        }
        let mut i: i64 = 0;
        while i < INDEX2DTYPE.len() as i64 {
            inverse[INDEX2DTYPE[i as usize] as usize] = i;
            i += 1;
        }
        inverse
    }

    pub const DTYPE2INDEX: [i64; ScalarType::NumOptions as usize] = calculate_dtype2index();
    pub const NUM_PROMOTE_TYPES: usize = 13;

    // Should match _promoteTypesLookup in c10/core/ScalarType.cpp so that
    // we match PyTorch core type promotion semantics.
    pub const PROMOTE_TYPES_LOOKUP: [[ScalarType; NUM_PROMOTE_TYPES]; NUM_PROMOTE_TYPES] = [
        /*        u1  i1  i2  i4  i8  f2  f4  f8  c2  c4  c8  b1  bf*/
        /* u1 */
        [U1, I2, I2, I4, I8, F2, F4, F8, C2, C4, C8, U1, BF],
        /* i1 */ [I2, I1, I2, I4, I8, F2, F4, F8, C2, C4, C8, I1, BF],
        /* i2 */ [I2, I2, I2, I4, I8, F2, F4, F8, C2, C4, C8, I2, BF],
        /* i4 */ [I4, I4, I4, I4, I8, F2, F4, F8, C2, C4, C8, I4, BF],
        /* i8 */ [I8, I8, I8, I8, I8, F2, F4, F8, C2, C4, C8, I8, BF],
        /* f2 */ [F2, F2, F2, F2, F2, F2, F4, F8, C2, C4, C8, F2, F4],
        /* f4 */ [F4, F4, F4, F4, F4, F4, F4, F8, C4, C4, C8, F4, F4],
        /* f8 */ [F8, F8, F8, F8, F8, F8, F8, F8, C8, C8, C8, F8, F8],
        /* c2 */ [C2, C2, C2, C2, C2, C2, C4, C8, C2, C4, C8, C2, C4],
        /* c4 */ [C4, C4, C4, C4, C4, C4, C4, C8, C4, C4, C8, C4, C4],
        /* c8 */ [C8, C8, C8, C8, C8, C8, C8, C8, C8, C8, C8, C8, C8],
        /* b1 */ [U1, I1, I2, I4, I8, F2, F4, F8, C2, C4, C8, B1, BF],
        /* bf */ [BF, BF, BF, BF, BF, F4, F4, F8, C4, C4, C8, BF, BF],
    ];
}

/// Implements type promotion rules that are consistent with ATen behaviour,
/// which in turn is consistent with NumPy's promote_types.
/// If half_to_float is set to true, then half and bfloat16 will be promoted to
/// float instead.
// [spec:et:def:scalar-type-util.executorch.runtime.promote-types]
// [spec:et:def:scalar-type-util.executorch.runtime.promote-types-fn]
// [spec:et:sem:scalar-type-util.executorch.runtime.promote-types-fn]
pub fn promote_types(a: ScalarType, b: ScalarType, half_to_float: bool) -> ScalarType {
    // For QInt types, only allow exact match
    if is_qint_type(a) && a == b {
        return a;
    }
    if is_qint_type(a) || is_qint_type(b) {
        et_check_msg!(false, "promoteTypes not valid for quantized dtypes");
    }

    // For Bits types, only allow exact match
    if is_bits_type(a) && a == b {
        return a;
    }
    if is_bits_type(a) || is_bits_type(b) {
        et_check_msg!(false, "promoteTypes not valid for bits dtypes");
    }

    // For Float8 types, only allow exact match
    if is_float8_type(a) && a == b {
        return a;
    }
    if is_float8_type(a) || is_float8_type(b) {
        et_check_msg!(false, "promoteTypes not valid for float8 dtypes");
    }

    // For barebones uint types, only allow exact match
    if is_barebones_unsigned_type(a) && a == b {
        return a;
    }
    if is_barebones_unsigned_type(a) || is_barebones_unsigned_type(b) {
        et_check_msg!(false, "promoteTypes not valid for barebone unsigned dtypes");
    }

    let ix_a = internal::DTYPE2INDEX[a as usize as usize];
    et_check!(ix_a != -1);
    let ix_b = internal::DTYPE2INDEX[b as usize as usize];
    et_check!(ix_b != -1);
    let mut promoted_type: ScalarType =
        internal::PROMOTE_TYPES_LOOKUP[ix_a as usize][ix_b as usize];

    if half_to_float && (promoted_type == ScalarType::Half || promoted_type == ScalarType::BFloat16)
    {
        promoted_type = ScalarType::Float;
    }

    promoted_type
}

//
// et_switch_*_types! macro family
//
// Literal port of the ET_SWITCH_<SET>_TYPES(dtype, ctx, name, CTYPE, body)
// family. Following PORTING.md's established shape, the Rust macro takes the
// dtype expr plus a `|CTYPE| { ... }` closure and expands to a match over the
// ScalarType arms in the set, binding a concrete `type CTYPE = <ctype>;` alias
// inside each arm before invoking the body.
//
// The `default` (unhandled dtype) arm mirrors ET_INTERNAL_SWITCH's fall-through
// (fail-fn): it records InvalidArgument on the context and logs an error, then
// yields the body's default value.
//
// [spec:et:def:scalar-type-util.executorch.runtime.fail-fn]
// [spec:et:sem:scalar-type-util.executorch.runtime.fail-fn]

/// One `case` of an internal switch: expands to a `(ScalarVariant, cpp_type)`
/// tuple of tokens consumed by `et_internal_switch!`. A `macro_rules!` invocation
/// cannot itself expand to a `match` arm (Rust forbids macros in arm position),
/// so the arm is built by `et_internal_switch!` from these token pairs instead.
#[macro_export]
macro_rules! et_internal_switch_case {
    ($scalar:ident, $cpp_type:ty) => {
        ($scalar, $cpp_type)
    };
}

/// The internal switch scaffold. `$ctx` is the KernelRuntimeContext, `$name` the
/// diagnostic op-name label, `$type` the runtime ScalarType, `$ctype_alias` the
/// per-arm concrete-type alias to bind, `$body` the shared body, and the
/// `($scalar, $cpp_type)` pairs the arms to emit. The default arm ports the
/// fail-fn behavior.
#[macro_export]
macro_rules! et_internal_switch {
    ($type:expr, $ctx:expr, $name:expr, $ctype_alias:ident, $body:expr,
        [ $( ($scalar:ident, $cpp_type:ty) ),* $(,)? ]) => {{
        let _st = $type;
        let et_switch_name = $name;
        let _ = et_switch_name;
        match _st {
            $(
                $crate::runtime::core::portable_type::scalar_type::ScalarType::$scalar => {
                    #[allow(non_camel_case_types, dead_code)]
                    type $ctype_alias = $cpp_type;
                    $body
                }
            )*
            // [spec:et:sem:scalar-type-util.executorch.runtime.fail-fn]
            _ => {
                $ctx.fail($crate::runtime::core::error::Error::InvalidArgument);
                $crate::et_log!(
                    Error,
                    "Unhandled dtype {} for {}",
                    $crate::runtime::core::exec_aten::util::scalar_type_util::to_string(_st),
                    et_switch_name
                );
                ::core::default::Default::default()
            }
        }
    }};
}

/// `ET_SWITCH_REAL_TYPES` — integer + float ctypes.
#[macro_export]
macro_rules! et_switch_real_types {
    ($type:expr, $ctx:expr, $name:expr, $ctype_alias:ident, $body:expr) => {
        $crate::et_internal_switch!(
            $type,
            $ctx,
            $name,
            $ctype_alias,
            $body,
            [
                (Byte, u8),
                (Char, i8),
                (Short, i16),
                (Int, i32),
                (Long, i64),
                (Float, f32),
                (Double, f64),
            ]
        )
    };
}

/// `ET_SWITCH_INT_TYPES` — integer ctypes.
#[macro_export]
macro_rules! et_switch_int_types {
    ($type:expr, $ctx:expr, $name:expr, $ctype_alias:ident, $body:expr) => {
        $crate::et_internal_switch!(
            $type,
            $ctx,
            $name,
            $ctype_alias,
            $body,
            [
                (Byte, u8),
                (Char, i8),
                (Short, i16),
                (Int, i32),
                (Long, i64),
            ]
        )
    };
}

/// `ET_SWITCH_FLOAT_TYPES` — float ctypes.
#[macro_export]
macro_rules! et_switch_float_types {
    ($type:expr, $ctx:expr, $name:expr, $ctype_alias:ident, $body:expr) => {
        $crate::et_internal_switch!(
            $type,
            $ctx,
            $name,
            $ctype_alias,
            $body,
            [(Float, f32), (Double, f64),]
        )
    };
}

/// `ET_SWITCH_REALHBBF16_TYPES` — real + Half + Bool + BFloat16 ctypes.
#[macro_export]
macro_rules! et_switch_realhbbf16_types {
    ($type:expr, $ctx:expr, $name:expr, $ctype_alias:ident, $body:expr) => {
        $crate::et_internal_switch!(
            $type,
            $ctx,
            $name,
            $ctype_alias,
            $body,
            [
                (Byte, u8),
                (Char, i8),
                (Short, i16),
                (Int, i32),
                (Long, i64),
                (Float, f32),
                (Double, f64),
                (Half, $crate::runtime::core::portable_type::Half),
                (Bool, bool),
                (BFloat16, $crate::runtime::core::portable_type::BFloat16),
            ]
        )
    };
}

/// `ET_SWITCH_ALL_TYPES` — every ScalarType covered by ET_FORALL_SCALAR_TYPES.
#[macro_export]
macro_rules! et_switch_all_types {
    ($type:expr, $ctx:expr, $name:expr, $ctype_alias:ident, $body:expr) => {
        $crate::et_internal_switch!(
            $type,
            $ctx,
            $name,
            $ctype_alias,
            $body,
            [
                (Byte, u8),
                (Char, i8),
                (Short, i16),
                (Int, i32),
                (Long, i64),
                (Float, f32),
                (Double, f64),
                (Half, $crate::runtime::core::portable_type::Half),
                (BFloat16, $crate::runtime::core::portable_type::BFloat16),
                (Bool, bool),
                (
                    ComplexHalf,
                    $crate::runtime::core::portable_type::ComplexHalf
                ),
                (
                    ComplexFloat,
                    $crate::runtime::core::portable_type::ComplexFloat
                ),
                (
                    ComplexDouble,
                    $crate::runtime::core::portable_type::ComplexDouble
                ),
                (
                    QInt8,
                    $crate::runtime::core::portable_type::qint_types::qint8
                ),
                (
                    QUInt8,
                    $crate::runtime::core::portable_type::qint_types::quint8
                ),
                (
                    QInt32,
                    $crate::runtime::core::portable_type::qint_types::qint32
                ),
                (
                    QUInt4x2,
                    $crate::runtime::core::portable_type::qint_types::quint4x2
                ),
                (
                    QUInt2x4,
                    $crate::runtime::core::portable_type::qint_types::quint2x4
                ),
                (
                    Bits1x8,
                    $crate::runtime::core::portable_type::bits_types::bits1x8
                ),
                (
                    Bits2x4,
                    $crate::runtime::core::portable_type::bits_types::bits2x4
                ),
                (
                    Bits4x2,
                    $crate::runtime::core::portable_type::bits_types::bits4x2
                ),
                (
                    Bits8,
                    $crate::runtime::core::portable_type::bits_types::bits8
                ),
                (
                    Bits16,
                    $crate::runtime::core::portable_type::bits_types::bits16
                ),
            ]
        )
    };
}

/// `ET_SWITCH_REALHBF16_TYPES` — real + Half + BFloat16 ctypes (NO Bool).
#[macro_export]
macro_rules! et_switch_realhbf16_types {
    ($type:expr, $ctx:expr, $name:expr, $ctype_alias:ident, $body:expr) => {
        $crate::et_internal_switch!(
            $type,
            $ctx,
            $name,
            $ctype_alias,
            $body,
            [
                (Byte, u8),
                (Char, i8),
                (Short, i16),
                (Int, i32),
                (Long, i64),
                (Float, f32),
                (Double, f64),
                (Half, $crate::runtime::core::portable_type::Half),
                (BFloat16, $crate::runtime::core::portable_type::BFloat16),
            ]
        )
    };
}

/// `ET_SWITCH_REALB_TYPES` — real + Bool ctypes.
#[macro_export]
macro_rules! et_switch_realb_types {
    ($type:expr, $ctx:expr, $name:expr, $ctype_alias:ident, $body:expr) => {
        $crate::et_internal_switch!(
            $type,
            $ctx,
            $name,
            $ctype_alias,
            $body,
            [
                (Byte, u8),
                (Char, i8),
                (Short, i16),
                (Int, i32),
                (Long, i64),
                (Float, f32),
                (Double, f64),
                (Bool, bool),
            ]
        )
    };
}

/// `ET_SWITCH_FLOATHBF16_TYPES` — Float, Double, Half, BFloat16 ctypes.
#[macro_export]
macro_rules! et_switch_floathbf16_types {
    ($type:expr, $ctx:expr, $name:expr, $ctype_alias:ident, $body:expr) => {
        $crate::et_internal_switch!(
            $type,
            $ctx,
            $name,
            $ctype_alias,
            $body,
            [
                (Float, f32),
                (Double, f64),
                (Half, $crate::runtime::core::portable_type::Half),
                (BFloat16, $crate::runtime::core::portable_type::BFloat16),
            ]
        )
    };
}

/// `ET_SWITCH_FLOATH_TYPES` — Half, Float, Double ctypes (no BFloat16).
#[macro_export]
macro_rules! et_switch_floath_types {
    ($type:expr, $ctx:expr, $name:expr, $ctype_alias:ident, $body:expr) => {
        $crate::et_internal_switch!(
            $type,
            $ctx,
            $name,
            $ctype_alias,
            $body,
            [
                (Float, f32),
                (Double, f64),
                (Half, $crate::runtime::core::portable_type::Half),
            ]
        )
    };
}

/// `ET_SWITCH_COMPLEXH_TYPES` — ComplexHalf, ComplexFloat, ComplexDouble ctypes.
#[macro_export]
macro_rules! et_switch_complexh_types {
    ($type:expr, $ctx:expr, $name:expr, $ctype_alias:ident, $body:expr) => {
        $crate::et_internal_switch!(
            $type,
            $ctx,
            $name,
            $ctype_alias,
            $body,
            [
                (
                    ComplexHalf,
                    $crate::runtime::core::portable_type::ComplexHalf
                ),
                (
                    ComplexFloat,
                    $crate::runtime::core::portable_type::ComplexFloat
                ),
                (
                    ComplexDouble,
                    $crate::runtime::core::portable_type::ComplexDouble
                ),
            ]
        )
    };
}

/// `ET_SWITCH_FLOATHBF16_TYPES_AND` — Float, Double, Half, BFloat16 ctypes plus
/// one additional ScalarType arm supplied as the leading literal (only `Long` is
/// used by the ported callers). Reproduces `ET_SWITCH_FLOATHBF16_TYPES_AND(Long,
/// ...)`.
#[macro_export]
macro_rules! et_switch_floathbf16_types_and {
    (Long, $type:expr, $ctx:expr, $name:expr, $ctype_alias:ident, $body:expr) => {
        $crate::et_internal_switch!(
            $type,
            $ctx,
            $name,
            $ctype_alias,
            $body,
            [
                (Float, f32),
                (Double, f64),
                (Half, $crate::runtime::core::portable_type::Half),
                (BFloat16, $crate::runtime::core::portable_type::BFloat16),
                (Long, i64),
            ]
        )
    };
}

/// `ET_SWITCH_INT_TYPES_AND` — integer ctypes plus one additional ScalarType
/// arm supplied as the leading literal (only `Bool` is used by the ported
/// callers). Reproduces `ET_SWITCH_INT_TYPES_AND(Bool, ...)`.
#[macro_export]
macro_rules! et_switch_int_types_and {
    (Bool, $type:expr, $ctx:expr, $name:expr, $ctype_alias:ident, $body:expr) => {
        $crate::et_internal_switch!(
            $type,
            $ctx,
            $name,
            $ctype_alias,
            $body,
            [
                (Byte, u8),
                (Char, i8),
                (Short, i16),
                (Int, i32),
                (Long, i64),
                (Bool, bool),
            ]
        )
    };
}

/// `ET_SWITCH_REAL_TYPES_AND` — real (integer + float) ctypes plus one
/// additional ScalarType arm supplied as the leading literal (only `Bool` is
/// used by the ported callers). Reproduces `ET_SWITCH_REAL_TYPES_AND(Bool, ...)`.
#[macro_export]
macro_rules! et_switch_real_types_and {
    (Bool, $type:expr, $ctx:expr, $name:expr, $ctype_alias:ident, $body:expr) => {
        $crate::et_internal_switch!(
            $type,
            $ctx,
            $name,
            $ctype_alias,
            $body,
            [
                (Byte, u8),
                (Char, i8),
                (Short, i16),
                (Int, i32),
                (Long, i64),
                (Float, f32),
                (Double, f64),
                (Bool, bool),
            ]
        )
    };
}

/// `ET_SWITCH_TWO_TYPES` — dispatch over exactly two named ScalarTypes.
///
/// PORT-NOTE: the C++ `ET_SWITCH_TWO_TYPES(T1, T2, ...)` is generic over any two
/// scalar-type names via per-type `ET_INTERNAL_SWITCH_CASE_##T` helpers. This
/// port provides the concrete arms needed by the elementwise dtype machinery
/// (`Bool, Byte`); add further arms here as call sites require them.
#[macro_export]
macro_rules! et_switch_two_types {
    (Bool, Byte, $type:expr, $ctx:expr, $name:expr, $ctype_alias:ident, $body:expr) => {
        $crate::et_internal_switch!(
            $type,
            $ctx,
            $name,
            $ctype_alias,
            $body,
            [(Bool, bool), (Byte, u8),]
        )
    };
    (Int, Long, $type:expr, $ctx:expr, $name:expr, $ctype_alias:ident, $body:expr) => {
        $crate::et_internal_switch!(
            $type,
            $ctx,
            $name,
            $ctype_alias,
            $body,
            [(Int, i32), (Long, i64),]
        )
    };
    (Long, Int, $type:expr, $ctx:expr, $name:expr, $ctype_alias:ident, $body:expr) => {
        $crate::et_internal_switch!(
            $type,
            $ctx,
            $name,
            $ctype_alias,
            $body,
            [(Long, i64), (Int, i32),]
        )
    };
    (Byte, Char, $type:expr, $ctx:expr, $name:expr, $ctype_alias:ident, $body:expr) => {
        $crate::et_internal_switch!(
            $type,
            $ctx,
            $name,
            $ctype_alias,
            $body,
            [(Byte, u8), (Char, i8),]
        )
    };
    (Float, Half, $type:expr, $ctx:expr, $name:expr, $ctype_alias:ident, $body:expr) => {
        $crate::et_internal_switch!(
            $type,
            $ctx,
            $name,
            $ctype_alias,
            $body,
            [
                (Float, f32),
                (Half, $crate::runtime::core::portable_type::Half),
            ]
        )
    };
}

/// `ET_SWITCH_FLOAT_TYPES_AND` — Float, Double ctypes plus one additional
/// ScalarType arm supplied as the leading literal (only `Half` is used by the
/// ported callers). Reproduces `ET_SWITCH_FLOAT_TYPES_AND(Half, ...)`.
#[macro_export]
macro_rules! et_switch_float_types_and {
    (Half, $type:expr, $ctx:expr, $name:expr, $ctype_alias:ident, $body:expr) => {
        $crate::et_internal_switch!(
            $type,
            $ctx,
            $name,
            $ctype_alias,
            $body,
            [
                (Float, f32),
                (Double, f64),
                (Half, $crate::runtime::core::portable_type::Half),
            ]
        )
    };
}

/// `ET_SWITCH_THREE_TYPES` — dispatch over exactly three named ScalarTypes.
///
/// PORT-NOTE: as with `et_switch_two_types!`, this port provides the concrete
/// arms needed by the elementwise dtype machinery (`Float, Half, BFloat16`).
#[macro_export]
macro_rules! et_switch_three_types {
    (Float, Half, BFloat16, $type:expr, $ctx:expr, $name:expr, $ctype_alias:ident, $body:expr) => {
        $crate::et_internal_switch!(
            $type,
            $ctx,
            $name,
            $ctype_alias,
            $body,
            [
                (Float, f32),
                (Half, $crate::runtime::core::portable_type::Half),
                (BFloat16, $crate::runtime::core::portable_type::BFloat16),
            ]
        )
    };
}

// Literal port of runtime/core/exec_aten/util/test/scalar_type_util_test.cpp.
#[cfg(test)]
mod tests {
    use super::*;
    use crate::runtime::core::portable_type::qint_types::{
        qint8, qint32, quint2x4, quint4x2, quint8,
    };

    // PORT-NOTE: the C++ `static_cast<ScalarType>(127)` / `(-1)` produce enum
    // values outside the declared discriminant set. The Rust `#[repr(i8)]`
    // `ScalarType` cannot legally hold those bit patterns: even a
    // `transmute::<i8, ScalarType>(127)` traps (Rust inserts an enum-validity
    // check that aborts non-unwinding), so the value can never even reach a
    // function under test. Those two out-of-range cases are therefore recorded
    // rather than ported; the in-range special value `NumOptions` (a declared
    // discriminant) still exercises the "not a real scalar type" behavior.

    // [spec:et:sem:scalar-type-util.executorch.runtime.to-string-fn/test]
    #[test]
    fn scalar_type_util_test_to_string() {
        // Some known types.
        assert_eq!(to_string(ScalarType::Int), "Int");
        assert_eq!(to_string(ScalarType::ComplexHalf), "ComplexHalf");

        // Undefined, which is sort of a special case since it's not part of the
        // iteration macros but is still a part of the enum.
        assert_eq!(to_string(ScalarType::Undefined), "Undefined");

        // NumOptions is not really a scalar type; the C++ `default` arm maps it to
        // "UNKNOWN_SCALAR".
        assert_eq!(to_string(ScalarType::NumOptions), "UNKNOWN_SCALAR");

        // PORT-NOTE: `toString(static_cast<ScalarType>(127))` and
        // `toString(static_cast<ScalarType>(-1))` are omitted: those bit patterns
        // cannot be represented by the `repr(i8)` `ScalarType` (a `transmute`
        // traps before the call), and `to_string`'s exhaustive match has no
        // `default` arm. Recorded, not ported.
    }

    // [spec:et:sem:scalar-type-util.executorch.runtime.element-size-fn/test]
    #[test]
    fn scalar_type_util_test_element_size() {
        struct TestCase {
            ty: ScalarType,
            expected_size: usize,
        }
        let test_cases = [
            TestCase {
                ty: ScalarType::Byte,
                expected_size: core::mem::size_of::<u8>(),
            },
            TestCase {
                ty: ScalarType::Char,
                expected_size: core::mem::size_of::<i8>(),
            },
            TestCase {
                ty: ScalarType::Short,
                expected_size: core::mem::size_of::<i16>(),
            },
            TestCase {
                ty: ScalarType::Int,
                expected_size: core::mem::size_of::<i32>(),
            },
            TestCase {
                ty: ScalarType::Long,
                expected_size: core::mem::size_of::<i64>(),
            },
            TestCase {
                ty: ScalarType::Half,
                expected_size: core::mem::size_of::<Half>(),
            },
            TestCase {
                ty: ScalarType::Float,
                expected_size: core::mem::size_of::<f32>(),
            },
            TestCase {
                ty: ScalarType::Double,
                expected_size: core::mem::size_of::<f64>(),
            },
            TestCase {
                ty: ScalarType::ComplexHalf,
                expected_size: core::mem::size_of::<ComplexHalf>(),
            },
            TestCase {
                ty: ScalarType::ComplexFloat,
                expected_size: core::mem::size_of::<ComplexFloat>(),
            },
            TestCase {
                ty: ScalarType::ComplexDouble,
                expected_size: core::mem::size_of::<ComplexDouble>(),
            },
            TestCase {
                ty: ScalarType::Bool,
                expected_size: core::mem::size_of::<bool>(),
            },
            TestCase {
                ty: ScalarType::QInt8,
                expected_size: core::mem::size_of::<qint8>(),
            },
            TestCase {
                ty: ScalarType::QUInt8,
                expected_size: core::mem::size_of::<quint8>(),
            },
            TestCase {
                ty: ScalarType::QInt32,
                expected_size: core::mem::size_of::<qint32>(),
            },
            TestCase {
                ty: ScalarType::BFloat16,
                expected_size: core::mem::size_of::<BFloat16>(),
            },
            TestCase {
                ty: ScalarType::QUInt4x2,
                expected_size: core::mem::size_of::<quint4x2>(),
            },
            TestCase {
                ty: ScalarType::QUInt2x4,
                expected_size: core::mem::size_of::<quint2x4>(),
            },
        ];
        for test_case in test_cases.iter() {
            assert_eq!(element_size(test_case.ty), test_case.expected_size);
        }
    }

    // [spec:et:sem:scalar-type-util.executorch.runtime.is-valid-fn/test]
    #[test]
    fn scalar_type_util_test_is_valid_true() {
        // Some valid types.
        assert!(is_valid(ScalarType::Byte));
        assert!(is_valid(ScalarType::Float));
        assert!(is_valid(ScalarType::ComplexFloat));
        assert!(is_valid(ScalarType::Bits16));
    }

    // [spec:et:sem:scalar-type-util.executorch.runtime.is-valid-fn/test]
    #[test]
    fn scalar_type_util_test_is_valid_false() {
        // Undefined, which is sort of a special case since it's not part of the
        // iteration macros but is still a part of the enum.
        assert!(!is_valid(ScalarType::Undefined));

        // NumOptions is not really a scalar type.
        assert!(!is_valid(ScalarType::NumOptions));

        // PORT-NOTE: `isValid(static_cast<ScalarType>(127))` / `(-1)` are omitted:
        // those out-of-range bit patterns cannot be materialized as a `repr(i8)`
        // `ScalarType` (`transmute` traps), so they can never reach `is_valid`.
        // Recorded, not ported.
    }

    // PORT-NOTE: `UnknownTypeElementSizeDies` is a death test — `element_size`
    // aborts via the PAL abort path (`runtime_abort` -> `libc::abort()`), which
    // terminates the process rather than unwinding, so `#[should_panic]` cannot
    // catch it; ported and `#[ignore]`d. The out-of-range (`127`/`-1`) variants
    // additionally require matching over an invalid `repr(i8)` value (UB), so
    // only the `Undefined` variant is expressed.
    // [spec:et:sem:scalar-type-util.executorch.runtime.element-size-fn/test]
    #[test]
    #[should_panic]
    #[ignore]
    fn scalar_type_util_test_unknown_type_element_size_dies() {
        let _ = element_size(ScalarType::Undefined);
    }

    // [spec:et:sem:scalar-type-util.executorch.runtime.can-cast-fn/test]
    #[test]
    fn scalar_type_util_test_can_cast_test() {
        // Check some common cases

        // complex to non-complex fails
        assert!(!can_cast(ScalarType::ComplexFloat, ScalarType::Float));
        assert!(!can_cast(ScalarType::ComplexDouble, ScalarType::Double));

        // non-complex to complex is fine
        assert!(can_cast(ScalarType::Float, ScalarType::ComplexFloat));
        assert!(can_cast(ScalarType::Float, ScalarType::ComplexDouble));
        assert!(can_cast(ScalarType::Int, ScalarType::ComplexDouble));

        // float to integral fails
        assert!(!can_cast(ScalarType::Float, ScalarType::Int));
        assert!(!can_cast(ScalarType::Double, ScalarType::Long));

        // integral to float in fine
        assert!(can_cast(ScalarType::Int, ScalarType::Float));
        assert!(can_cast(ScalarType::Long, ScalarType::Float));

        // non-bool to bool fails
        assert!(!can_cast(ScalarType::Byte, ScalarType::Bool));
        assert!(!can_cast(ScalarType::Int, ScalarType::Bool));

        // bool to non-bool is fine
        assert!(can_cast(ScalarType::Bool, ScalarType::Byte));
        assert!(can_cast(ScalarType::Bool, ScalarType::Int));
        assert!(can_cast(ScalarType::Bool, ScalarType::Float));
    }

    // [spec:et:sem:scalar-type-util.executorch.runtime.promote-types-fn/test]
    // also verifies internal::calculate_dtype2index: the asserted promotions are
    // looked up through internal::DTYPE2INDEX, which is built by
    // calculate_dtype2index at const-eval time; a wrong inverse table (e.g. a
    // stale -1 for a promotable dtype, or a wrong index) would make these
    // assertions fail.
    // [spec:et:sem:scalar-type-util.executorch.runtime.internal.calculate-dtype2index-fn/test]
    #[test]
    fn scalar_type_util_test_promote_types_test() {
        // Check some common cases

        assert_eq!(
            promote_types(ScalarType::Float, ScalarType::Double, false),
            ScalarType::Double
        );
        assert_eq!(
            promote_types(ScalarType::Float, ScalarType::Short, false),
            ScalarType::Float
        );

        assert_eq!(
            promote_types(ScalarType::Float, ScalarType::Int, false),
            ScalarType::Float
        );
        assert_eq!(
            promote_types(ScalarType::Long, ScalarType::Float, false),
            ScalarType::Float
        );

        assert_eq!(
            promote_types(ScalarType::Bool, ScalarType::Bool, false),
            ScalarType::Bool
        );

        assert_eq!(
            promote_types(ScalarType::Byte, ScalarType::Int, false),
            ScalarType::Int
        );
        assert_eq!(
            promote_types(ScalarType::Char, ScalarType::Bool, false),
            ScalarType::Char
        );
        assert_eq!(
            promote_types(ScalarType::Bool, ScalarType::Int, false),
            ScalarType::Int
        );

        assert_eq!(
            promote_types(ScalarType::BFloat16, ScalarType::Half, false),
            ScalarType::Float
        );
        assert_eq!(
            promote_types(ScalarType::BFloat16, ScalarType::Bool, false),
            ScalarType::BFloat16
        );
    }

    // PORT-NOTE: the C++ scalar_type_util_test.cpp suite only tests toString,
    // elementSize, isValid, canCast, and promoteTypes. The remaining pure
    // predicate/converter helpers below have no C++ test surface; these focused
    // unit tests pin their behavior against the C++ header semantics (the sem
    // rules in docs/spec/port are the referee), matching the ET_FORALL_* sets.

    // ET_FORALL_INT_TYPES + optionally Bool.
    // [spec:et:sem:scalar-type-util.executorch.runtime.is-integral-type-fn/test]
    #[test]
    fn scalar_type_util_test_is_integral_type() {
        for t in [
            ScalarType::Byte,
            ScalarType::Char,
            ScalarType::Short,
            ScalarType::Int,
            ScalarType::Long,
        ] {
            assert!(is_integral_type(t, false));
            assert!(is_integral_type(t, true));
        }
        // Bool counts only when include_bool is set.
        assert!(!is_integral_type(ScalarType::Bool, false));
        assert!(is_integral_type(ScalarType::Bool, true));
        // Floats/complex/quantized are never integral.
        for t in [
            ScalarType::Half,
            ScalarType::Float,
            ScalarType::Double,
            ScalarType::BFloat16,
            ScalarType::ComplexFloat,
            ScalarType::QInt8,
        ] {
            assert!(!is_integral_type(t, false));
            assert!(!is_integral_type(t, true));
        }
    }

    // Double, Float, Half, BFloat16.
    // [spec:et:sem:scalar-type-util.executorch.runtime.is-floating-type-fn/test]
    #[test]
    fn scalar_type_util_test_is_floating_type() {
        for t in [
            ScalarType::Double,
            ScalarType::Float,
            ScalarType::Half,
            ScalarType::BFloat16,
        ] {
            assert!(is_floating_type(t));
        }
        for t in [
            ScalarType::Byte,
            ScalarType::Int,
            ScalarType::Long,
            ScalarType::Bool,
            ScalarType::ComplexFloat,
            ScalarType::QInt8,
        ] {
            assert!(!is_floating_type(t));
        }
    }

    // ComplexHalf, ComplexFloat, ComplexDouble.
    // [spec:et:sem:scalar-type-util.executorch.runtime.is-complex-type-fn/test]
    #[test]
    fn scalar_type_util_test_is_complex_type() {
        for t in [
            ScalarType::ComplexHalf,
            ScalarType::ComplexFloat,
            ScalarType::ComplexDouble,
        ] {
            assert!(is_complex_type(t));
        }
        for t in [
            ScalarType::Float,
            ScalarType::Double,
            ScalarType::Half,
            ScalarType::Int,
            ScalarType::Bool,
        ] {
            assert!(!is_complex_type(t));
        }
    }

    // ET_FORALL_REAL_TYPES: Byte, Char, Short, Int, Long, Float, Double.
    // [spec:et:sem:scalar-type-util.executorch.runtime.is-real-type-fn/test]
    #[test]
    fn scalar_type_util_test_is_real_type() {
        for t in [
            ScalarType::Byte,
            ScalarType::Char,
            ScalarType::Short,
            ScalarType::Int,
            ScalarType::Long,
            ScalarType::Float,
            ScalarType::Double,
        ] {
            assert!(is_real_type(t));
        }
        // Half/Bool/BFloat16/complex are NOT plain-real.
        for t in [
            ScalarType::Half,
            ScalarType::Bool,
            ScalarType::BFloat16,
            ScalarType::ComplexFloat,
        ] {
            assert!(!is_real_type(t));
        }
    }

    // real + Half.
    // [spec:et:sem:scalar-type-util.executorch.runtime.is-real-h-type-fn/test]
    #[test]
    fn scalar_type_util_test_is_real_h_type() {
        assert!(is_real_h_type(ScalarType::Half));
        assert!(is_real_h_type(ScalarType::Int));
        assert!(is_real_h_type(ScalarType::Double));
        assert!(!is_real_h_type(ScalarType::Bool));
        assert!(!is_real_h_type(ScalarType::BFloat16));
        assert!(!is_real_h_type(ScalarType::ComplexHalf));
    }

    // real + Half + Bool.
    // [spec:et:sem:scalar-type-util.executorch.runtime.is-real-hb-type-fn/test]
    #[test]
    fn scalar_type_util_test_is_real_hb_type() {
        assert!(is_real_hb_type(ScalarType::Half));
        assert!(is_real_hb_type(ScalarType::Bool));
        assert!(is_real_hb_type(ScalarType::Long));
        assert!(!is_real_hb_type(ScalarType::BFloat16));
        assert!(!is_real_hb_type(ScalarType::ComplexFloat));
    }

    // real + Half + BFloat16 (NO Bool).
    // [spec:et:sem:scalar-type-util.executorch.runtime.is-real-hbf16-type-fn/test]
    #[test]
    fn scalar_type_util_test_is_real_hbf16_type() {
        assert!(is_real_hbf16_type(ScalarType::Half));
        assert!(is_real_hbf16_type(ScalarType::BFloat16));
        assert!(is_real_hbf16_type(ScalarType::Float));
        assert!(!is_real_hbf16_type(ScalarType::Bool));
        assert!(!is_real_hbf16_type(ScalarType::ComplexFloat));
    }

    // real + Half + Bool + BFloat16.
    // [spec:et:sem:scalar-type-util.executorch.runtime.is-real-hbbf16-type-fn/test]
    #[test]
    fn scalar_type_util_test_is_real_hbbf16_type() {
        assert!(is_real_hbbf16_type(ScalarType::Half));
        assert!(is_real_hbbf16_type(ScalarType::Bool));
        assert!(is_real_hbbf16_type(ScalarType::BFloat16));
        assert!(is_real_hbbf16_type(ScalarType::Int));
        assert!(!is_real_hbbf16_type(ScalarType::ComplexFloat));
        assert!(!is_real_hbbf16_type(ScalarType::QInt8));
    }

    // Bits1x8, Bits2x4, Bits4x2, Bits8, Bits16.
    // [spec:et:sem:scalar-type-util.executorch.runtime.is-bits-type-fn/test]
    #[test]
    fn scalar_type_util_test_is_bits_type() {
        for t in [
            ScalarType::Bits1x8,
            ScalarType::Bits2x4,
            ScalarType::Bits4x2,
            ScalarType::Bits8,
            ScalarType::Bits16,
        ] {
            assert!(is_bits_type(t));
        }
        assert!(!is_bits_type(ScalarType::Byte));
        assert!(!is_bits_type(ScalarType::QInt8));
    }

    // QInt8, QUInt8, QInt32, QUInt4x2, QUInt2x4.
    // [spec:et:sem:scalar-type-util.executorch.runtime.is-q-int-type-fn/test]
    #[test]
    fn scalar_type_util_test_is_q_int_type() {
        for t in [
            ScalarType::QInt8,
            ScalarType::QUInt8,
            ScalarType::QInt32,
            ScalarType::QUInt4x2,
            ScalarType::QUInt2x4,
        ] {
            assert!(is_qint_type(t));
        }
        assert!(!is_qint_type(ScalarType::Byte));
        assert!(!is_qint_type(ScalarType::Bits8));
    }

    // Float8_e5m2, Float8_e4m3fn, Float8_e5m2fnuz, Float8_e4m3fnuz.
    // [spec:et:sem:scalar-type-util.executorch.runtime.is-float8-type-fn/test]
    #[test]
    fn scalar_type_util_test_is_float8_type() {
        for t in [
            ScalarType::Float8_e5m2,
            ScalarType::Float8_e4m3fn,
            ScalarType::Float8_e5m2fnuz,
            ScalarType::Float8_e4m3fnuz,
        ] {
            assert!(is_float8_type(t));
        }
        assert!(!is_float8_type(ScalarType::Float));
        assert!(!is_float8_type(ScalarType::Half));
    }

    // UInt16, UInt32, UInt64.
    // [spec:et:sem:scalar-type-util.executorch.runtime.is-barebones-unsigned-type-fn/test]
    #[test]
    fn scalar_type_util_test_is_barebones_unsigned_type() {
        for t in [ScalarType::UInt16, ScalarType::UInt32, ScalarType::UInt64] {
            assert!(is_barebones_unsigned_type(t));
        }
        // Byte (uint8) is NOT a "barebones unsigned" type.
        assert!(!is_barebones_unsigned_type(ScalarType::Byte));
        assert!(!is_barebones_unsigned_type(ScalarType::Int));
    }

    // Byte->QUInt8, Char->QInt8, Int->QInt32; else identity.
    // [spec:et:sem:scalar-type-util.executorch.runtime.to-q-int-type-fn/test]
    #[test]
    fn scalar_type_util_test_to_q_int_type() {
        assert_eq!(to_q_int_type(ScalarType::Byte), ScalarType::QUInt8);
        assert_eq!(to_q_int_type(ScalarType::Char), ScalarType::QInt8);
        assert_eq!(to_q_int_type(ScalarType::Int), ScalarType::QInt32);
        // Unmapped types pass through unchanged.
        assert_eq!(to_q_int_type(ScalarType::Short), ScalarType::Short);
        assert_eq!(to_q_int_type(ScalarType::Float), ScalarType::Float);
    }

    // QUInt8->Byte, QInt8->Char, QInt32->Int, QUInt4x2->Byte, QUInt2x4->Byte;
    // else identity.
    // [spec:et:sem:scalar-type-util.executorch.runtime.to-underlying-fn/test]
    #[test]
    fn scalar_type_util_test_to_underlying() {
        assert_eq!(to_underlying(ScalarType::QUInt8), ScalarType::Byte);
        assert_eq!(to_underlying(ScalarType::QInt8), ScalarType::Char);
        assert_eq!(to_underlying(ScalarType::QInt32), ScalarType::Int);
        assert_eq!(to_underlying(ScalarType::QUInt4x2), ScalarType::Byte);
        assert_eq!(to_underlying(ScalarType::QUInt2x4), ScalarType::Byte);
        assert_eq!(to_underlying(ScalarType::Float), ScalarType::Float);
    }

    // is_underlying(t, q) == (t == to_underlying(q)).
    // [spec:et:sem:scalar-type-util.executorch.runtime.is-underlying-fn/test]
    #[test]
    fn scalar_type_util_test_is_underlying() {
        assert!(is_underlying(ScalarType::Byte, ScalarType::QUInt8));
        assert!(is_underlying(ScalarType::Char, ScalarType::QInt8));
        assert!(is_underlying(ScalarType::Int, ScalarType::QInt32));
        assert!(is_underlying(ScalarType::Byte, ScalarType::QUInt4x2));
        assert!(!is_underlying(ScalarType::Char, ScalarType::QUInt8));
        // Non-quantized q maps to itself, so only an equal ty is "underlying".
        assert!(is_underlying(ScalarType::Float, ScalarType::Float));
        assert!(!is_underlying(ScalarType::Int, ScalarType::Float));
    }

    // complex categories are signed; ints/floats follow numeric_limits::is_signed;
    // Byte (uint8) and Bool are unsigned.
    // [spec:et:sem:scalar-type-util.executorch.runtime.is-signed-type-fn/test]
    #[test]
    fn scalar_type_util_test_is_signed_type() {
        for t in [
            ScalarType::ComplexHalf,
            ScalarType::ComplexFloat,
            ScalarType::ComplexDouble,
            ScalarType::Char,
            ScalarType::Short,
            ScalarType::Int,
            ScalarType::Long,
            ScalarType::Float,
            ScalarType::Double,
            ScalarType::Half,
            ScalarType::BFloat16,
        ] {
            assert!(is_signed_type(t));
        }
        assert!(!is_signed_type(ScalarType::Byte));
        assert!(!is_signed_type(ScalarType::Bool));
    }

    // Complex->real value type; else identity.
    // [spec:et:sem:scalar-type-util.executorch.runtime.to-real-value-type-fn/test]
    #[test]
    fn scalar_type_util_test_to_real_value_type() {
        assert_eq!(
            to_real_value_type(ScalarType::ComplexHalf),
            ScalarType::Half
        );
        assert_eq!(
            to_real_value_type(ScalarType::ComplexFloat),
            ScalarType::Float
        );
        assert_eq!(
            to_real_value_type(ScalarType::ComplexDouble),
            ScalarType::Double
        );
        assert_eq!(to_real_value_type(ScalarType::Float), ScalarType::Float);
        assert_eq!(to_real_value_type(ScalarType::Int), ScalarType::Int);
    }

    // real/complex float -> complex type; BFloat16 maps to ComplexFloat.
    // [spec:et:sem:scalar-type-util.executorch.runtime.to-complex-type-fn/test]
    #[test]
    fn scalar_type_util_test_to_complex_type() {
        assert_eq!(
            to_complex_type(ScalarType::BFloat16),
            ScalarType::ComplexFloat
        );
        assert_eq!(to_complex_type(ScalarType::Half), ScalarType::ComplexHalf);
        assert_eq!(to_complex_type(ScalarType::Float), ScalarType::ComplexFloat);
        assert_eq!(
            to_complex_type(ScalarType::Double),
            ScalarType::ComplexDouble
        );
        assert_eq!(
            to_complex_type(ScalarType::ComplexHalf),
            ScalarType::ComplexHalf
        );
        assert_eq!(
            to_complex_type(ScalarType::ComplexFloat),
            ScalarType::ComplexFloat
        );
        assert_eq!(
            to_complex_type(ScalarType::ComplexDouble),
            ScalarType::ComplexDouble
        );
    }

    // convert mirrors static_cast<To>(val) for the non-float->integral overload.
    // [spec:et:sem:scalar-type-util.executorch.runtime.convert-fn/test]
    #[test]
    fn scalar_type_util_test_convert() {
        // widening int -> float
        let f: f64 = convert::<f64, i32>(7);
        assert_eq!(f, 7.0);
        // int -> wider int
        let l: i64 = convert::<i64, i16>(-3);
        assert_eq!(l, -3);
        // identity
        let x: f32 = convert::<f32, f32>(2.5);
        assert_eq!(x, 2.5);
    }

    // The internal-switch default (fail-fn) arm: an unhandled dtype records
    // InvalidArgument on the context and yields the body's Default value.
    // [spec:et:sem:scalar-type-util.executorch.runtime.fail-fn/test]
    #[test]
    fn scalar_type_util_test_switch_fail_fn() {
        use crate::runtime::core::error::Error;
        use crate::runtime::core::memory_allocator::{MemoryAllocator, MemoryAllocatorBase};
        use crate::runtime::kernel::kernel_runtime_context::KernelRuntimeContext;

        // The fail-fn default arm calls et_log!, which requires the PAL to be
        // initialized (mirrors the C++ fixtures' runtime_init()).
        crate::runtime::platform::runtime::runtime_init();

        let null_tracer = crate::extension::module::module::null_event_tracer();
        let null_alloc = core::ptr::null_mut::<MemoryAllocator>() as *mut dyn MemoryAllocatorBase;

        let mut ctx = KernelRuntimeContext::new(null_tracer, null_alloc);
        // Bool is not in ET_SWITCH_REAL_TYPES, so it hits the fail-fn default arm.
        let out: i32 =
            crate::et_switch_real_types!(ScalarType::Bool, ctx, "switch_fail_fn_test", CTYPE, {
                core::mem::size_of::<CTYPE>() as i32
            });
        assert_eq!(out, i32::default());
        assert_eq!(ctx.failure_state(), Error::InvalidArgument);

        // A handled dtype runs the body and leaves the context Ok.
        let mut ctx_ok = KernelRuntimeContext::new(null_tracer, null_alloc);
        let sz: i32 =
            crate::et_switch_real_types!(ScalarType::Int, ctx_ok, "switch_fail_fn_test", CTYPE, {
                core::mem::size_of::<CTYPE>() as i32
            });
        assert_eq!(sz, 4);
        assert_eq!(ctx_ok.failure_state(), Error::Ok);
    }

    // PORT-NOTE: `compileTypePromoteTypesTest` compares the compile-time
    // `promote_types<T1, T2, half_to_float>::type` template against the runtime
    // `promoteTypes`. This port has no compile-time (type-level) promote-types
    // machinery — only the runtime `promote_types` free function — so the test
    // has no Rust surface to bind to and is recorded here rather than ported.
    // Its runtime companion (`promoteTypesTest`) is fully ported above.
}
